In [2]:
import pandas as pd

In [3]:
train=pd.read_csv('train.csv')

In [4]:
test=pd.read_csv('test.csv')

In [5]:
train.head()

Id   Open Date        City  City Group Type  P1   P2   P3   P4  P5  ...  \
0   0  07/17/1999    İstanbul  Big Cities   IL   4  5.0  4.0  4.0   2  ...   
1   1  02/14/2008      Ankara  Big Cities   FC   4  5.0  4.0  4.0   1  ...   
2   2  03/09/2013  Diyarbakır       Other   IL   2  4.0  2.0  5.0   2  ...   
3   3  02/02/2012       Tokat       Other   IL   6  4.5  6.0  6.0   4  ...   
4   4  05/09/2009   Gaziantep       Other   IL   3  4.0  3.0  4.0   2  ...   

   P29  P30  P31  P32  P33  P34  P35  P36  P37    revenue  
0  3.0    5    3    4    5    5    4    3    4  5653753.0  
1  3.0    0    0    0    0    0    0    0    0  6923131.0  
2  3.0    0    0    0    0    0    0    0    0  2055379.0  
3  7.5   25   12   10    6   18   12   12    6  2675511.0  
4  3.0    5    1    3    2    3    4    3    3  4316715.0  

[5 rows x 43 columns]

In [6]:
train=train.drop(['Id','Open Date'],axis=1)

In [7]:
train.head()

City  City Group Type  P1   P2   P3   P4  P5  P6  P7  ...  P29  P30  \
0    İstanbul  Big Cities   IL   4  5.0  4.0  4.0   2   2   5  ...  3.0    5   
1      Ankara  Big Cities   FC   4  5.0  4.0  4.0   1   2   5  ...  3.0    0   
2  Diyarbakır       Other   IL   2  4.0  2.0  5.0   2   3   5  ...  3.0    0   
3       Tokat       Other   IL   6  4.5  6.0  6.0   4   4  10  ...  7.5   25   
4   Gaziantep       Other   IL   3  4.0  3.0  4.0   2   2   5  ...  3.0    5   

   P31  P32  P33  P34  P35  P36  P37    revenue  
0    3    4    5    5    4    3    4  5653753.0  
1    0    0    0    0    0    0    0  6923131.0  
2    0    0    0    0    0    0    0  2055379.0  
3   12   10    6   18   12   12    6  2675511.0  
4    1    3    2    3    4    3    3  4316715.0  

[5 rows x 41 columns]

In [8]:
from sklearn import preprocessing

In [9]:
label_encoder = preprocessing.LabelEncoder()

In [10]:
train['City']= label_encoder.fit_transform(train['City'])

In [11]:
train['City Group']= label_encoder.fit_transform(train['City Group'])

In [12]:
train['Type']= label_encoder.fit_transform(train['Type'])

In [13]:
test['Type']= label_encoder.fit_transform(test['Type'])

In [14]:
test['City']= label_encoder.fit_transform(test['City'])

In [15]:
test['City Group']= label_encoder.fit_transform(test['City Group'])

In [16]:
train.head()

City  City Group  Type  P1   P2   P3   P4  P5  P6  P7  ...  P29  P30  P31  \
0    31           0     2   4  5.0  4.0  4.0   2   2   5  ...  3.0    5    3   
1     3           0     1   4  5.0  4.0  4.0   1   2   5  ...  3.0    0    0   
2    10           1     2   2  4.0  2.0  5.0   2   3   5  ...  3.0    0    0   
3    28           1     2   6  4.5  6.0  6.0   4   4  10  ...  7.5   25   12   
4    14           1     2   3  4.0  3.0  4.0   2   2   5  ...  3.0    5    1   

   P32  P33  P34  P35  P36  P37    revenue  
0    4    5    5    4    3    4  5653753.0  
1    0    0    0    0    0    0  6923131.0  
2    0    0    0    0    0    0  2055379.0  
3   10    6   18   12   12    6  2675511.0  
4    3    2    3    4    3    3  4316715.0  

[5 rows x 41 columns]

In [17]:
test.head()

Id   Open Date  City  City Group  Type  P1   P2   P3   P4  P5  ...  P28  \
0   0  01/22/2011    38           1     1   1  4.0  4.0  4.0   1  ...  2.0   
1   1  03/18/2011    27           1     2   3  4.0  4.0  4.0   2  ...  1.0   
2   2  10/30/2013     3           0     1   3  4.0  4.0  4.0   2  ...  2.0   
3   3  05/06/2013    26           1     2   2  4.0  4.0  4.0   2  ...  2.0   
4   4  07/31/2013     1           1     1   2  4.0  4.0  4.0   1  ...  5.0   

   P29  P30  P31  P32  P33  P34  P35  P36  P37  
0  3.0    0    0    0    0    0    0    0    0  
1  3.0    0    0    0    0    0    0    0    0  
2  3.0    0    0    0    0    0    0    0    0  
3  3.0    0    4    0    0    0    0    0    0  
4  3.0    0    0    0    0    0    0    0    0  

[5 rows x 42 columns]

In [18]:
test=test.drop(['Id','Open Date'],axis=1)

In [19]:
test.head()

City  City Group  Type  P1   P2   P3   P4  P5  P6  P7  ...  P28  P29  P30  \
0    38           1     1   1  4.0  4.0  4.0   1   2   5  ...  2.0  3.0    0   
1    27           1     2   3  4.0  4.0  4.0   2   2   5  ...  1.0  3.0    0   
2     3           0     1   3  4.0  4.0  4.0   2   2   5  ...  2.0  3.0    0   
3    26           1     2   2  4.0  4.0  4.0   2   3   5  ...  2.0  3.0    0   
4     1           1     1   2  4.0  4.0  4.0   1   2   5  ...  5.0  3.0    0   

   P31  P32  P33  P34  P35  P36  P37  
0    0    0    0    0    0    0    0  
1    0    0    0    0    0    0    0  
2    0    0    0    0    0    0    0  
3    4    0    0    0    0    0    0  
4    0    0    0    0    0    0    0  

[5 rows x 40 columns]

In [20]:
train.head()

City  City Group  Type  P1   P2   P3   P4  P5  P6  P7  ...  P29  P30  P31  \
0    31           0     2   4  5.0  4.0  4.0   2   2   5  ...  3.0    5    3   
1     3           0     1   4  5.0  4.0  4.0   1   2   5  ...  3.0    0    0   
2    10           1     2   2  4.0  2.0  5.0   2   3   5  ...  3.0    0    0   
3    28           1     2   6  4.5  6.0  6.0   4   4  10  ...  7.5   25   12   
4    14           1     2   3  4.0  3.0  4.0   2   2   5  ...  3.0    5    1   

   P32  P33  P34  P35  P36  P37    revenue  
0    4    5    5    4    3    4  5653753.0  
1    0    0    0    0    0    0  6923131.0  
2    0    0    0    0    0    0  2055379.0  
3   10    6   18   12   12    6  2675511.0  
4    3    2    3    4    3    3  4316715.0  

[5 rows x 41 columns]

In [21]:
x =train.drop(['revenue'],axis=1)
y =train['revenue']

In [22]:
x.head()

City  City Group  Type  P1   P2   P3   P4  P5  P6  P7  ...  P28  P29  P30  \
0    31           0     2   4  5.0  4.0  4.0   2   2   5  ...  2.0  3.0    5   
1     3           0     1   4  5.0  4.0  4.0   1   2   5  ...  3.0  3.0    0   
2    10           1     2   2  4.0  2.0  5.0   2   3   5  ...  1.0  3.0    0   
3    28           1     2   6  4.5  6.0  6.0   4   4  10  ...  2.5  7.5   25   
4    14           1     2   3  4.0  3.0  4.0   2   2   5  ...  1.0  3.0    5   

   P31  P32  P33  P34  P35  P36  P37  
0    3    4    5    5    4    3    4  
1    0    0    0    0    0    0    0  
2    0    0    0    0    0    0    0  
3   12   10    6   18   12   12    6  
4    1    3    2    3    4    3    3  

[5 rows x 40 columns]

In [23]:
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import metrics


In [24]:
ctree = tree.DecisionTreeClassifier()

In [25]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=.3,random_state=1)

In [26]:
ctree.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [27]:
ctree.feature_importances_

array([0.03191489, 0.03191489, 0.0212766 , 0.03191489, 0.04255319,
       0.05319149, 0.05319149, 0.04255319, 0.04255319, 0.05319149,
       0.03191489, 0.03191489, 0.03191489, 0.05319149, 0.0106383 ,
       0.03191489, 0.0106383 , 0.        , 0.0106383 , 0.        ,
       0.0106383 , 0.04255319, 0.0212766 , 0.03191489, 0.0212766 ,
       0.04255319, 0.        , 0.0212766 , 0.0212766 , 0.        ,
       0.05319149, 0.04255319, 0.0106383 , 0.03191489, 0.0212766 ,
       0.        , 0.        , 0.0106383 , 0.        , 0.        ])

In [28]:
feature_imp = pd.DataFrame()
feature_imp['col']=x.columns
feature_imp['imp']=ctree.feature_importances_*100
feature_imp.sort_values('imp',ascending=False)


col       imp
30         P28  5.319149
5           P3  5.319149
6           P4  5.319149
9           P7  5.319149
13         P11  5.319149
21         P19  4.255319
4           P2  4.255319
7           P5  4.255319
8           P6  4.255319
31         P29  4.255319
25         P23  4.255319
15         P13  3.191489
1   City Group  3.191489
23         P21  3.191489
33         P31  3.191489
0         City  3.191489
12         P10  3.191489
10          P8  3.191489
3           P1  3.191489
11          P9  3.191489
24         P22  2.127660
22         P20  2.127660
27         P25  2.127660
34         P32  2.127660
28         P26  2.127660
2         Type  2.127660
32         P30  1.063830
37         P35  1.063830
20         P18  1.063830
18         P16  1.063830
16         P14  1.063830
14         P12  1.063830
29         P27  0.000000
26         P24  0.000000
19         P17  0.000000
17         P15  0.000000
35         P33  0.000000
36         P34  0.000000
38         P36  0.000000
39         P37  0.000000

In [29]:
rtree = tree.DecisionTreeRegressor()

In [30]:
rtree

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [31]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=100)

In [32]:
ctree.feature_importances_

array([0.03191489, 0.03191489, 0.0212766 , 0.03191489, 0.04255319,
       0.05319149, 0.05319149, 0.04255319, 0.04255319, 0.05319149,
       0.03191489, 0.03191489, 0.03191489, 0.05319149, 0.0106383 ,
       0.03191489, 0.0106383 , 0.        , 0.0106383 , 0.        ,
       0.0106383 , 0.04255319, 0.0212766 , 0.03191489, 0.0212766 ,
       0.04255319, 0.        , 0.0212766 , 0.0212766 , 0.        ,
       0.05319149, 0.04255319, 0.0106383 , 0.03191489, 0.0212766 ,
       0.        , 0.        , 0.0106383 , 0.        , 0.        ])

In [33]:
feature_imp = pd.DataFrame()
feature_imp['col']=x.columns
feature_imp['imp']=ctree.feature_importances_*100
feature_imp.sort_values('imp',ascending=False)

col       imp
30         P28  5.319149
5           P3  5.319149
6           P4  5.319149
9           P7  5.319149
13         P11  5.319149
21         P19  4.255319
4           P2  4.255319
7           P5  4.255319
8           P6  4.255319
31         P29  4.255319
25         P23  4.255319
15         P13  3.191489
1   City Group  3.191489
23         P21  3.191489
33         P31  3.191489
0         City  3.191489
12         P10  3.191489
10          P8  3.191489
3           P1  3.191489
11          P9  3.191489
24         P22  2.127660
22         P20  2.127660
27         P25  2.127660
34         P32  2.127660
28         P26  2.127660
2         Type  2.127660
32         P30  1.063830
37         P35  1.063830
20         P18  1.063830
18         P16  1.063830
16         P14  1.063830
14         P12  1.063830
29         P27  0.000000
26         P24  0.000000
19         P17  0.000000
17         P15  0.000000
35         P33  0.000000
36         P34  0.000000
38         P36  0.000000
39         P37  0.000000

In [34]:
x1=x.drop(['P9','P27','P16','P7','P32','P17','P34','P33','P6','P35','P36','P26','P25','P24','P37','P10','P14'],axis=1)

In [35]:
y1=y

In [36]:
x1.head()

City  City Group  Type  P1   P2   P3   P4  P5  P8  P11  ...  P18  P19  P20  \
0    31           0     2   4  5.0  4.0  4.0   2   4    3  ...    4    5    4   
1     3           0     1   4  5.0  4.0  4.0   1   5    1  ...    0    3    2   
2    10           1     2   2  4.0  2.0  5.0   2   5    2  ...    0    1    1   
3    28           1     2   6  4.5  6.0  6.0   4   8    8  ...   12   20   12   
4    14           1     2   3  4.0  3.0  4.0   2   5    2  ...    4    2    2   

   P21  P22  P23  P28  P29  P30  P31  
0    1    3    3  2.0  3.0    5    3  
1    1    3    2  3.0  3.0    0    0  
2    1    1    1  1.0  3.0    0    0  
3    6    1   10  2.5  7.5   25   12  
4    1    2    1  1.0  3.0    5    1  

[5 rows x 23 columns]

In [37]:
y1.head()

0    5653753.0
1    6923131.0
2    2055379.0
3    2675511.0
4    4316715.0
Name: revenue, dtype: float64

In [38]:
rtree = tree.DecisionTreeRegressor()

In [39]:
rtree

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x1, y1, test_size=0.3, random_state=100)

In [41]:
y_train.head()

74     5500818.0
70     3982767.0
22     3956086.0
131    3199619.0
126    4015749.0
Name: revenue, dtype: float64

In [42]:
y_train.shape

(95,)

In [43]:
rtree_model = rtree.fit(x_train, y_train)

In [44]:
y_test_pred = rtree_model.predict(x_test)

In [45]:
comp_df = x_test.copy()
comp_df['actual'] = y_test
comp_df['predicted'] = y_test_pred
comp_df.head(5)

City  City Group  Type  P1   P2   P3   P4  P5  P8  P11  ...  P20  P21  \
136    31           0     1   4  5.0  3.0  5.0   2   4    4  ...    1    1   
123     7           1     1   1  1.0  4.0  3.0   1   4    3  ...    1    1   
92     31           0     1  12  7.5  7.5  6.0   2   8    8  ...   15    6   
106     4           1     1   3  3.0  6.0  6.0   4   8    6  ...    3    3   
77      3           0     1   3  5.0  3.0  5.0   3   4    5  ...    5    1   

     P22  P23   P28  P29  P30  P31     actual   predicted  
136    1    1   3.0  3.0    0    0  6363241.0  12579319.5  
123    1    1   2.0  3.0    0    0  4263629.0   3570392.0  
92     3   25  10.0  7.5    0    0  6782425.0   4780607.0  
106    1    5   2.5  7.5    0    0  4888774.0   4067566.0  
77     3    1   3.0  2.0    0    0  1904842.0   4219263.0  

[5 rows x 25 columns]

In [46]:
import numpy as np

In [47]:
y_train_pred = rtree_model.predict(x_train)
print(np.sqrt(metrics.mean_squared_error(y_train, y_train_pred)))

1032732.7809139793


In [48]:
import numpy as np
y_test_pred = rtree_model.predict(x_test)
np.sqrt(metrics.mean_squared_error(y_test, y_test_pred))

3876329.628558165

In [49]:
y_null = np.zeros_like(y_test, dtype=float)
y_null.fill(y_test.mean())
y_null[1:10]

array([4647836.02380952, 4647836.02380952, 4647836.02380952,
       4647836.02380952, 4647836.02380952, 4647836.02380952,
       4647836.02380952, 4647836.02380952, 4647836.02380952])

In [50]:
np.sqrt(metrics.mean_squared_error(y_test, y_null)) 

2968206.1563993534

In [51]:
temp_imp = pd.DataFrame()
temp_imp['col'] = x1.columns
temp_imp['imp'] = rtree.feature_importances_*100

temp_imp

col        imp
0         City  15.062571
1   City Group   0.086826
2         Type   0.363309
3           P1   9.593899
4           P2   4.205751
5           P3   3.078241
6           P4   2.808812
7           P5   0.154955
8           P8   0.008005
9          P11  15.739527
10         P12   3.158454
11         P13   0.000000
12         P15   2.439572
13         P18   2.259633
14         P19   0.681332
15         P20   8.321696
16         P21   2.247274
17         P22  15.449939
18         P23   1.050448
19         P28   8.264137
20         P29   2.851123
21         P30   0.090183
22         P31   2.084315

In [52]:
# Depth Tuning 
rtree = tree.DecisionTreeRegressor(max_depth=3) # 2, 3, 4
rtree.fit(x_train, y_train)
y_pred = rtree.predict(x_test)
np.sqrt(metrics.mean_squared_error(y_test, y_pred))

3604166.7659323397

In [53]:
from sklearn.model_selection import GridSearchCV

In [54]:
param_grid = { "criterion"      : ['mse', 'mae'],    
               "max_features"   : [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15], 
               "max_depth"      : [1,2,3],
               "splitter"       : ['best', 'random'],
               "min_samples_leaf"  : [ 1,2,3,4,5,6,7,8]
                }

In [55]:
optimized_tree = GridSearchCV(rtree_model, param_grid, scoring = 'neg_mean_absolute_error', cv = 5)

In [56]:
optimized_tree.fit(x_train, y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'criterion': ['mse', 'mae'], 'max_features': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], 'max_depth': [1, 2, 3], 'splitter': ['best', 'random'], 'min_samples_leaf': [1, 2, 3, 4, 5, 6, 7, 8]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='neg_mean_absolute_error', verbose=0)

In [57]:
optimized_tree.best_params_

{'criterion': 'mae',
 'max_depth': 3,
 'max_features': 5,
 'min_samples_leaf': 8,
 'splitter': 'random'}

In [58]:
optimized_tree.best_estimator_

DecisionTreeRegressor(criterion='mae', max_depth=3, max_features=5,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=8,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='random')

In [59]:
optimized_tree.best_score_

-1372807.4157894736

In [60]:
rtree_final = optimized_tree.best_estimator_
rtree_final

DecisionTreeRegressor(criterion='mae', max_depth=3, max_features=5,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=8,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='random')

In [61]:
# y_test_pred = rtree_final.predict(x_test)
print(np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))

3876329.628558165


In [62]:
import pickle
pickle.dump(rtree_final, open('restuatrantprobmodel.pk', 'wb'))

In [63]:
from sklearn.datasets import load_boston
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeRegressor
boston = load_boston()

cross_val_score(rtree, boston.data, boston.target, cv=10)


array([ 0.56006348,  0.41686357, -0.57285385,  0.6658676 ,  0.71503066,
       -0.15940576, -0.71147248,  0.31600345, -2.47610321, -0.05007233])